# -*- coding: utf-8 -*-
"""iris-flower-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zzWJFiu6161Cg0FoEnNGKDMBopjHsbu

**Install Dependencies**
"""

!pip install -q scikit-learn pandas matplotlib seaborn joblib

"""Import Libraries"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

import joblib

"""File Upload"""

from google.colab import files
import io

print("Upload your Iris CSV file (optional):")
uploaded = files.upload()

"""Load Dataset"""

iris = load_iris()

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Convert numeric labels to names
df['species'] = df['species'].map({
    0: 'setosa',
    1: 'versicolor',
    2: 'virginica'
})

print(df.head())

"""Data Visualization"""

sns.pairplot(df, hue='species')
plt.show()

"""Feature & Target Split"""

X = df.drop('species', axis=1)
y = df['species']

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Feature Scaling"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""Baseline Model (Logistic Regression)"""

baseline_model = LogisticRegression(max_iter=200)
baseline_model.fit(X_train, y_train)

baseline_pred = baseline_model.predict(X_test)

print("Baseline Accuracy:", accuracy_score(y_test, baseline_pred))

"""Hyperparameter Tuning (GridSearchCV - Logistic Regression)"""

param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear'],
    'max_iter': [100, 200, 300]
}

grid_lr = GridSearchCV(
    LogisticRegression(),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

grid_lr.fit(X_train, y_train)

print("Best Parameters (LR):", grid_lr.best_params_)

"""Evaluate Tuned Logistic Model"""

best_lr = grid_lr.best_estimator_

y_pred_lr = best_lr.predict(X_test)

print("\nTuned Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:\n", classification_report(y_test, y_pred_lr))

cm_lr = confusion_matrix(y_test, y_pred_lr)
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""Hyperparameter Tuning (Random Forest)"""

rf_params = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10]
}

grid_rf = GridSearchCV(
    RandomForestClassifier(),
    rf_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

grid_rf.fit(X_train, y_train)

print("Best Parameters (RF):", grid_rf.best_params_)

"""Evaluate Tuned Random Forest"""

best_rf = grid_rf.best_estimator_

y_pred_rf = best_rf.predict(X_test)

print("\nRandom Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))

cm_rf = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Greens')
plt.title("Confusion Matrix - Random Forest")
plt.show()

"""Compare Models"""

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

"""Predict Custom Input"""

# Example input
sample = np.array([[5.1, 3.5, 1.4, 0.2]])

sample_scaled = scaler.transform(sample)

prediction = best_lr.predict(sample_scaled)

print("Predicted Species:", prediction[0])

"""Save Model"""

joblib.dump(best_lr, "best_iris_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model saved successfully!")